"""create payment_history table

Revision ID: 0367c4de61d3
Revises: 436085eb3159
Create Date: 2026-08-07 12:26:47.882891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0367c4de61d3'
down_revision: Union[str, Sequence[str], None] = '436085eb3159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upi_payment_id', sa.Integer(), nullable=True),
    sa.Column('card_payment_id', sa.Integer(), nullable=True),
    sa.Column('net_banking_payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_payment_id'], ['card_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['net_banking_payment_id'], ['net_banking_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upi_payment_id'], ['upi_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bookings', 'service_type',
               existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bookings', 'booking_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_table('payment_history')
    # ### end Alembic commands ###
