"""add field engineer professional details

Revision ID: 0a1e775debd0
Revises: 867c2e954cac
Create Date: 2026-09-04 12:05:17.332588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a1e775debd0'
down_revision: Union[str, Sequence[str], None] = '867c2e954cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_engineer_certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('degree_name', sa.String(length=255), nullable=True),
    sa.Column('institute_name', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('grade_percentage', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currently_working', sa.Boolean(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('technologies_used', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_licenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('license_name', sa.String(length=255), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


    op.add_column(
        'user_profiles',
        sa.Column('professional_summary', sa.Text(), nullable=True)
    )
    # op.drop_table('home_contactus')
    # op.drop_table('django_content_type')
    # op.drop_table('django_migrations')
    # op.drop_index(op.f('django_admin_log_content_type_id_c4bce8eb'), table_name='django_admin_log')
    # op.drop_index(op.f('django_admin_log_user_id_c564eba6'), table_name='django_admin_log')
    # op.drop_table('django_admin_log')
    # op.drop_index(op.f('auth_user_groups_group_id_97559544'), table_name='auth_user_groups')
    # op.drop_index(op.f('auth_user_groups_user_id_6a12ed8b'), table_name='auth_user_groups')
    # op.drop_table('auth_user_groups')
    # op.drop_index(op.f('auth_group_name_a6ea08ec_like'), table_name='auth_group', postgresql_ops={'name': 'varchar_pattern_ops'})
    # op.drop_table('auth_group')
    # op.drop_index(op.f('idx_fcm_device_tokens_token'), table_name='fcm_device_tokens')
    # op.drop_index(op.f('idx_fcm_device_tokens_user_id'), table_name='fcm_device_tokens')
    # op.drop_table('fcm_device_tokens')
    # op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    # op.drop_index(op.f('django_session_session_key_c0390e0f_like'), table_name='django_session', postgresql_ops={'session_key': 'varchar_pattern_ops'})
    # op.drop_table('django_session')
    # op.drop_table('home_salesenquiry')
    # op.drop_index(op.f('home_stayupdated_email_2bbb9e62_like'), table_name='home_stayupdated', postgresql_ops={'email': 'varchar_pattern_ops'})
    # op.drop_table('home_stayupdated')
    # op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    # op.drop_table('auth_permission')
    # op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    # op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    # op.drop_table('auth_group_permissions')
    # op.drop_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), table_name='auth_user_user_permissions')
    # op.drop_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), table_name='auth_user_user_permissions')
    # op.drop_table('auth_user_user_permissions')
    # op.drop_index(op.f('auth_user_username_6821ab7c_like'), table_name='auth_user', postgresql_ops={'username': 'varchar_pattern_ops'})
    # op.drop_table('auth_user')
    # op.drop_index(op.f('idx_notifications_user_created_at'), table_name='notifications')
    # op.drop_index(op.f('idx_notifications_user_is_read'), table_name='notifications')
    # op.drop_index(op.f('idx_notifications_user_type'), table_name='notifications')
    # op.drop_table('notifications')
    # op.drop_index(op.f('home_passwordresettoken_user_id_d9ae7619'), table_name='home_passwordresettoken')
    # op.drop_table('home_passwordresettoken')
    # op.drop_table('user_permissions')
    # op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    # op.drop_table('user_notification_preferences')
    # op.alter_column('access_information', 'visitor_pass_required',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('access_information', 'night_shift_access',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('access_information', 'weekend_access',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('access_information', 'id_verification_required',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            nullable=False)
    # op.drop_column('call_sessions', 'appointment_reference')
    # op.drop_column('call_sessions', 'appointment_id')
    # op.create_index(op.f('ix_chat_history_chat_session_id'), 'chat_history', ['chat_session_id'], unique=False)
    # op.create_index(op.f('ix_chat_history_sender_id'), 'chat_history', ['sender_id'], unique=False)
    # op.create_index(op.f('ix_chat_participants_chat_session_id'), 'chat_participants', ['chat_session_id'], unique=False)
    # op.create_index(op.f('ix_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_chat_session_user', 'chat_participants', ['chat_session_id', 'user_id'])
    # op.drop_index(op.f('ix_countries_id'), table_name='countries')
    # op.drop_constraint(op.f('engineer_invitations_referral_token_key'), 'engineer_invitations', type_='unique')
    # op.drop_index(op.f('ix_engineer_invitations_referral_token'), table_name='engineer_invitations')
    # op.create_index(op.f('ix_engineer_invitations_referral_token'), 'engineer_invitations', ['referral_token'], unique=True)
    # op.add_column('services', sa.Column('image_url', sa.String(length=500), nullable=True))
    # op.add_column('services', sa.Column('about_service', sa.Text(), nullable=True))
    # op.add_column('services', sa.Column('whats_included', sa.Text(), nullable=True))
    # op.add_column('services', sa.Column('min_duration_hours', sa.Integer(), nullable=False))
    # op.drop_index(op.f('ix_states_country_id'), table_name='states')
    # op.drop_index(op.f('ix_states_id'), table_name='states')
    # op.add_column('user_profiles', sa.Column('professional_summary', sa.Text(), nullable=True))
    # op.alter_column('users', 'mobile_number',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=20),
    #            existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    op.drop_column('user_profiles', 'professional_summary')

    op.drop_table('field_engineer_tools')
    op.drop_table('field_engineer_skills')
    op.drop_table('field_engineer_licenses')
    op.drop_table('field_engineer_experiences')
    op.drop_table('field_engineer_education')
    op.drop_table('field_engineer_certifications')