"""fix booking ids

Revision ID: 34f35f422019
Revises: 6e32fb03c798
Create Date: 2026-06-17 14:14:04.267741

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f35f422019'
down_revision: Union[str, Sequence[str], None] = '6e32fb03c798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade():
    op.drop_table("bookings")

    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("booking_number", sa.String(50), nullable=False, unique=True),
        sa.Column("service_type", sa.String(255)),
        sa.Column("description", sa.Text()),
        # sa.Column(
        #     "booking_status",
        #     sa.Enum(
        #         "PENDING",
        #         "CONFIRMED",
        #         "IN_PROGRESS",
        #         "COMPLETED",
        #         "CANCELLED",
        #         name="bookingstatus"
        #     )
        # ),
        sa.Column(
           "booking_status",
            ENUM(
                "PENDING",
                "CONFIRMED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="bookingstatus",
                create_type=False
            )
        ),
        sa.Column("scheduled_date", sa.String(50)),
        sa.Column("scheduled_time", sa.String(50)),
        sa.Column("address", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"))
    )



# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('bookings', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('bookings', 'user_id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
