"""add customer complete profile tables

Revision ID: 436085eb3159
Revises: fc3efa071e75
Create Date: 2026-07-21 14:29:29.275180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436085eb3159'
down_revision: Union[str, Sequence[str], None] = 'fc3efa071e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('gst_number', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('authorized_person_name', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id')
    )
    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('gst_certificate', sa.Text(), nullable=True),
    sa.Column('tax_identification_card', sa.Text(), nullable=True),
    sa.Column('company_registration_certificate', sa.Text(), nullable=True),
    sa.Column('moa_aoa', sa.Text(), nullable=True),
    sa.Column('bank_account_proof', sa.Text(), nullable=True),
    sa.Column('other_document', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id')
    )
    op.create_table('customer_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('identity_type', sa.String(length=100), nullable=True),
    sa.Column('identity_number', sa.String(length=255), nullable=True),
    sa.Column('front_image', sa.Text(), nullable=True),
    sa.Column('back_image', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_table('customer_identities')
    op.drop_table('customer_documents')
    op.drop_table('customer_businesses')
    # ### end Alembic commands ###
