"""convert uuid to integer

Revision ID: 4aebda0c7177
Revises: 34f35f422019
Create Date: 2026-06-17 17:40:20.004235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aebda0c7177'
down_revision: Union[str, Sequence[str], None] = '34f35f422019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_addresses', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_addresses', 'profile_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_addresses', 'profile_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_addresses', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
