# """booking uuid to integer

# Revision ID: 6e32fb03c798
# Revises: 75fd714b902e
# Create Date: 2026-06-17 13:12:46.692074

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '6e32fb03c798'
# down_revision: Union[str, Sequence[str], None] = '75fd714b902e'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     pass
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('bookings', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('bookings', 'user_id',
#                existing_type=sa.UUID(),
#                type_=sa.Integer(),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     pass
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('bookings', 'user_id',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('bookings', 'id',
#                existing_type=sa.Integer(),
#                type_=sa.UUID(),
#                existing_nullable=False,
#                autoincrement=True)
#     # ### end Alembic commands ###
from typing import Sequence, Union

revision: str = '6e32fb03c798'
down_revision: Union[str, Sequence[str], None] = '75fd714b902e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass