"""create vendor profile table

Revision ID: 97ba9c7a0075
Revises: 90cb87cda6e7
Create Date: 2026-07-20 13:11:03.669085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ba9c7a0075'
down_revision: Union[str, Sequence[str], None] = '90cb87cda6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('owner_manager_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_type', sa.String(length=100), nullable=True),
    sa.Column('legal_business_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('company_registration_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=100), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('years_in_business', sa.Integer(), nullable=True),
    sa.Column('company_registration_date', sa.Date(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('primary_service_category', sa.String(length=255), nullable=True),
    sa.Column('about_business', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('working_hours', sa.String(length=100), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            type_=sa.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=False)
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###
