"""add field engineer profile tables

Revision ID: c0a8358a1b54
Revises: d87a74e272a6
Create Date: 2026-07-07 18:49:19.167770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a8358a1b54'
down_revision: Union[str, Sequence[str], None] = 'd87a74e272a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_specializations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialization')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name')
    )
    op.create_table('years_of_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience')
    )
    op.create_table('field_engineer_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_engineer_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['field_engineer_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_engineer_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('identity_proof', sa.Text(), nullable=True),
    sa.Column('education_certificate', sa.Text(), nullable=True),
    sa.Column('work_company_id', sa.Text(), nullable=True),
    sa.Column('certification', sa.Text(), nullable=True),
    sa.Column('experience_certificate', sa.Text(), nullable=True),
    sa.Column('driving_license', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id')
    )
    op.create_table('field_engineer_service_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_engineer_id', sa.Integer(), nullable=False),
    sa.Column('primary_city', sa.String(length=100), nullable=True),
    sa.Column('service_radius', sa.Integer(), nullable=True),
    sa.Column('preferred_work_areas', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['field_engineer_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            nullable=False)
    op.add_column('user_profiles', sa.Column('is_associated_with_vendor', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('years_of_experience_id', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('primary_specialization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'user_profiles', 'primary_specializations', ['primary_specialization_id'], ['id'])
    op.create_foreign_key(None, 'user_profiles', 'years_of_experience', ['years_of_experience_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'primary_specialization_id')
    op.drop_column('user_profiles', 'years_of_experience_id')
    op.drop_column('user_profiles', 'vendor_id')
    op.drop_column('user_profiles', 'is_associated_with_vendor')
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            type_=sa.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=False)
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.drop_table('field_engineer_service_areas')
    op.drop_table('field_engineer_documents')
    op.drop_table('field_engineer_availability')
    op.drop_table('years_of_experience')
    op.drop_table('vendors')
    op.drop_table('primary_specializations')
    # ### end Alembic commands ###
