"""create help support tables

Revision ID: d87a74e272a6
Revises: f8e0e4e39b8f
Create Date: 2026-07-07 13:12:08.512199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87a74e272a6'
down_revision: Union[str, Sequence[str], None] = 'f8e0e4e39b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_issue_types_id'), 'issue_types', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_table('report_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_type_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_issues_id'), 'report_issues', ['id'], unique=False)
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            type_=sa.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=False)
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.drop_index(op.f('ix_report_issues_id'), table_name='report_issues')
    op.drop_table('report_issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_issue_types_id'), table_name='issue_types')
    op.drop_table('issue_types')
    # ### end Alembic commands ###
