"""create inappcall tables

Revision ID: e100a0a66853
Revises: 5b5c7eef8e36
Create Date: 2026-08-10 14:05:03.744233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e100a0a66853'
down_revision: Union[str, Sequence[str], None] = '5b5c7eef8e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.Enum('AUDIO', 'VIDEO', name='calltype'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RINGING', 'JOINED', 'ONGOING', 'ENDED', 'MISSED', 'REJECTED', 'CANCELLED', name='callstatus'), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('appointment_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('join_url', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_id'), 'call_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_call_sessions_room_id'), 'call_sessions', ['room_id'], unique=True)
    op.create_table('call_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('peer_name', sa.String(length=255), nullable=True),
    sa.Column('peer_avatar', sa.String(length=500), nullable=True),
    sa.Column('presenter', sa.Boolean(), nullable=True),
    sa.Column('audio_enabled', sa.Boolean(), nullable=True),
    sa.Column('video_enabled', sa.Boolean(), nullable=True),
    sa.Column('screen_enabled', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_participants_id'), 'call_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'service_type',
               existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bookings', 'booking_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_call_participants_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index(op.f('ix_call_sessions_room_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
