"""booking workflow tables v2

Revision ID: f8e0e4e39b8f
Revises: fbbf38710fe3
Create Date: 2026-06-18 14:44:10.882432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e0e4e39b8f'
down_revision: Union[str, Sequence[str], None] = 'fbbf38710fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_type_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_type_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('sub_service_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('entry_instructions', sa.Text(), nullable=True),
    sa.Column('security_gate_details', sa.Text(), nullable=True),
    sa.Column('parking_availability', sa.String(length=100), nullable=True),
    sa.Column('access_timing', sa.String(length=100), nullable=True),
    sa.Column('visitor_pass_required', sa.Integer(), nullable=True),
    sa.Column('night_shift_access', sa.Integer(), nullable=True),
    sa.Column('weekend_access', sa.Integer(), nullable=True),
    sa.Column('id_verification_required', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=20), nullable=True),
    sa.Column('area_locality', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=True),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=50), nullable=True),
    sa.Column('scheduled_time', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_contact_persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('contact_person_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('alternate_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('site_type_id', sa.Integer(), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.String(length=100), nullable=True),
    sa.Column('building_wing', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.ForeignKeyConstraint(['site_type_id'], ['site_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('budget_min', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('budget_max', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('sub_service_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('requirement_description', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('bid_status', sa.String(length=50), nullable=True))
    # op.alter_column('bookings', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('bookings', 'booking_number',
    #            existing_type=sa.VARCHAR(length=50),
    #            nullable=True)
    # op.alter_column('bookings', 'service_type',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
    #            nullable=False)
    op.create_foreign_key(None, 'bookings', 'sub_services', ['sub_service_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'service_type',
               existing_type=sa.Enum('LAPTOP_REPAIR', 'DESKTOP_REPAIR', 'NETWORK_ISSUE', 'SOFTWARE_INSTALLATION', name='servicetype'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bookings', 'booking_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'bid_status')
    op.drop_column('bookings', 'requirement_description')
    op.drop_column('bookings', 'sub_service_id')
    op.drop_column('bookings', 'service_id')
    op.drop_column('bookings', 'budget_max')
    op.drop_column('bookings', 'budget_min')
    op.drop_table('site_details')
    op.drop_table('site_contact_persons')
    op.drop_table('booking_schedules')
    op.drop_table('booking_documents')
    op.drop_table('booking_addresses')
    op.drop_table('access_information')
    op.drop_table('sub_services')
    op.drop_table('site_types')
    op.drop_table('services')
    op.drop_table('project_types')
    # ### end Alembic commands ###
